const axios = require('axios');
const fs = require('fs');

const SERVER_URL = 'http://localhost:3200'; // Clawyard port

// Test order payload
const testOrder = {
  stickers: [
    { id: 'cyberpunk-agent', qty: 1 }
  ],
  shippingAddress: {
    firstName: 'Test',
    lastName: 'Agent',
    company: 'AI Labs',
    address1: '123 Bot Street',
    city: 'San Francisco',
    stateCode: 'CA',
    countryCode: 'US',
    zip: '94107'
  },
  agentId: 'test-agent-erc8004'
};

async function testX402Payment() {
  console.log('🧪 Testing x402 payment implementation');
  console.log('===================================');
  
  try {
    // Step 1: Make request without payment (should get 402)
    console.log('1. Testing 402 Payment Required response...');
    
    try {
      const response = await axios.post(`${SERVER_URL}/api/order`, testOrder);
      console.log('❌ Expected 402, but got:', response.status);
    } catch (error) {
      if (error.response && error.response.status === 402) {
        console.log('✅ Got 402 Payment Required as expected');
        
        // Check payment requirements
        const paymentRequired = error.response.headers['payment-required'];
        if (paymentRequired) {
          console.log('✅ Payment-Required header present');
          
          try {
            const decoded = JSON.parse(Buffer.from(paymentRequired, 'base64').toString());
            console.log('✅ Payment requirements decoded successfully');
            console.log('Payment details:');
            console.log('  - Amount:', decoded.accepted.amount, 'USDC');
            console.log('  - Network:', decoded.accepted.network);
            console.log('  - Asset:', decoded.accepted.asset);
            console.log('  - PayTo:', decoded.accepted.payTo);
            console.log('  - Timeout:', decoded.accepted.maxTimeoutSeconds, 'seconds');
          } catch (decodeError) {
            console.log('❌ Failed to decode payment requirements');
          }
        } else {
          console.log('❌ Payment-Required header missing');
        }
        
        // Check response body
        const body = error.response.data;
        console.log('Response body:', JSON.stringify(body, null, 2));
      } else {
        console.log('❌ Expected 402, but got:', error.response?.status || 'no response');
      }
    }
    
    // Step 2: Test with invalid payment signature
    console.log('\n2. Testing invalid payment signature...');
    
    try {
      const response = await axios.post(`${SERVER_URL}/api/order`, testOrder, {
        headers: {
          'Payment-Signature': 'invalid-signature'
        }
      });
      console.log('❌ Expected 400, but got:', response.status);
    } catch (error) {
      if (error.response && error.response.status === 400) {
        console.log('✅ Got 400 Bad Request for invalid signature');
      } else if (error.response && error.response.status === 402) {
        console.log('✅ Got 402 Payment Verification Failed');
        console.log('Error:', error.response.data.message);
      } else {
        console.log('❌ Unexpected response:', error.response?.status);
      }
    }
    
    // Step 3: Test with mock valid payment
    console.log('\n3. Testing with mock payment signature...');
    
    // Create a mock payment payload (this would normally be generated by a client)
    const mockPayment = {
      x402Version: 2,
      resource: {
        url: 'https://clawyard.dev/api/order',
        description: 'Clawyard sticker purchase',
        mimeType: 'application/json'
      },
      accepted: {
        scheme: 'exact',
        network: 'eip155:8453',
        amount: '4990000', // $4.99 in USDC (6 decimals)
        asset: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
        payTo: getClawyardAddress(),
        maxTimeoutSeconds: 300,
        extra: {
          assetTransferMethod: 'eip3009',
          name: 'USDC',
          version: '2'
        }
      },
      payload: {
        signature: '0x2d6a7588d6acca505cbf0d9a4a227e0c52c6c34008c8e8986a1283259764173608a2ce6496642e377d6da8dbbf5836e9bd15092f9ecab05ded3d6293af148b571c',
        authorization: {
          from: '0x857b06519E91e3A54538791bDbb0E22373e36b66',
          to: getClawyard Address(),
          value: '4990000',
          validAfter: Math.floor(Date.now() / 1000) - 60,
          validBefore: Math.floor(Date.now() / 1000) + 300,
          nonce: '0xf3746613c2d920b5fdabc0856f2aeb2d4f88ee6037b8cc5d04a71a4462f13480'
        }
      }
    };
    
    const paymentSignature = Buffer.from(JSON.stringify(mockPayment)).toString('base64');
    
    try {
      const response = await axios.post(`${SERVER_URL}/api/order`, testOrder, {
        headers: {
          'Payment-Signature': paymentSignature
        }
      });
      
      console.log('✅ Order created successfully!');
      console.log('Order ID:', response.data.orderId);
      console.log('Payment method:', response.data.payment.method);
      console.log('Payment verified:', response.data.payment.verified);
      
    } catch (error) {
      if (error.response && error.response.status === 402) {
        console.log('⚠️  Payment verification failed (expected for mock data)');
        console.log('Error:', error.response.data.message);
      } else {
        console.log('❌ Unexpected error:', error.response?.status, error.response?.data);
      }
    }
    
    console.log('\n✅ x402 implementation test completed');
    
  } catch (error) {
    console.error('❌ Test failed:', error.message);
  }
}

function getClawyard Address() {
  try {
    return fs.readFileSync('/root/.secrets/clawyard-wallet-address', 'utf8').trim();
  } catch (error) {
    return '0xF400CA0182e697f6Bdb677b1D66Dc53810ad7E4C'; // Fallback to generated address
  }
}

// Run the test
if (require.main === module) {
  testX402Payment();
}

module.exports = { testX402Payment };